### ISSUE TITLE
Automatic installation fails - v1.6.1.0 [Windows 10]

### ISSUE THREAD

**Issue by kekukui** [midwan/amigula#5]
> **If these components are already installed, you can launch the application now. Otherwise, click the button below to install the prerequisites and run the application.** 
> 
> https://blitterstudio.com/files/publish.htm

![image](https://user-images.githubusercontent.com/20834957/80128927-5fe09900-8564-11ea-834b-0500bd58513b.png)

**--When I click the link, nothing happens**

**Comment by midwan** [comment]
@kekukui 
Did you try the Setup.exe installation or just the `Amigula.application` directly?
It seems to work fine here on my Win10 machine, Version 1909, OS build 18363.815.

Amigula generally needs an update, but it should still work if the requirements are met.
